In [142]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [184]:
import numpy as np 
from stabilizer import *

[autoreload of stabilizer failed: Traceback (most recent call last):
  File "/Users/shwetlanajha/opt/miniconda3/envs/qc-env/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/shwetlanajha/opt/miniconda3/envs/qc-env/lib/python3.8/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/Users/shwetlanajha/opt/miniconda3/envs/qc-env/lib/python3.8/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/shwetlanajha/opt/miniconda3/envs/qc-env/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen

In [185]:
x = sigmax()
z = sigmaz()
toffoli = np.kron(zero@ct(zero), np.eye(4))+np.kron(one@ct(one),cnot(0,1,2))

In [186]:
toffoli

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [155]:
print(toffoli@tensor([np.eye(2),np.eye(2),np.eye(2)])@toffoli)
print(tensor([np.eye(2), np.eye(2),np.eye(2)]))
#III->III

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [156]:
print(toffoli@tensor([z,np.eye(2),np.eye(2)])@toffoli)
print(tensor([z, np.eye(2),np.eye(2)]))
#ZII->ZII

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -0. -0. -0.]
 [ 0.  0.  0.  0. -0. -1. -0. -0.]
 [ 0.  0.  0.  0. -0. -0. -1. -0.]
 [ 0.  0.  0.  0. -0. -0. -0. -1.]]


In [13]:
print(toffoli@tensor([np.eye(2),z,np.eye(2)])@toffoli)
print(tensor([np.eye(2), z,np.eye(2)]))
#IZI->IZI

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -1.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -1. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -1.]]


In [160]:
print(toffoli@tensor([np.eye(2),np.eye(2),z])@toffoli)
print(tensor([z,z,z]))
#IIZ->III

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
[[ 0  1  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  1  0]]


In [191]:
print(toffoli@tensor([z,z,np.eye(2)])@toffoli)
print(tensor([z, z,np.eye(2)]))
toffoli@tensor([z,z,np.eye(2)])@toffoli - tensor([z, z,np.eye(2)])
#ZZI->ZZI

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0.  0.  0.]
 [ 0.  0. -0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -0.  0.  0.]
 [ 0.  0.  0.  0. -0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
print(toffoli@tensor([np.eye(2),z,z])@toffoli)
print(tensor([ z,-1*z, -1*z]))
#IZZ->III

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]
[[ 1  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 -1]]


In [ ]:
print(toffoli@tensor([np.eye(2),np.eye(2),np.eye(2)])@toffoli)
print(tensor([np.eye(2), np.eye(2),np.eye(2)]))
#ZIZ->III

In [187]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z, z,z]))
#ZZZ->III

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
[[ 1  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 -1]]


In [204]:
print(toffoli@tensor([x,np.eye(2),np.eye(2)])@toffoli)
print(tensor([z,x, z]))
#XII->III

array([[ 0.,  0., -1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0., -1.,  0.,  0.]])

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#IXI->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#IIX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#XXI->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#XIX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#IXX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#XXX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#ZXX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#XZX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#XXZ->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#ZZX->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#XZZ->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#ZXZ->III

In [ ]:
print(toffoli@tensor([z,z,z])@toffoli)
print(tensor([z,z,z]))
#ZZZ->III

testing apply toffoli

In [181]:
apply_toffoli('110',0,1,2)

'111'