In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import numpy as np 
from stabilizer import *

In [24]:
cx = cnot(0,1,2)
I = np.eye(2)
x = sigmax()
z = sigmaz()
op = tensor([x,x])
cx@op@cx, tensor([x,I])

(array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]))

In [ ]:
print(cnot(0,1,2)@tensor([np.eye(2),np.eye(2)])@cnot(0,1,2))
print(tensor([np.eye(2), np.eye(2)]))
#II->II

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(cnot(0,1,2)@tensor([z,np.eye(2)])@cnot(0,1,2))
print(tensor([z, np.eye(2)]))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1. -0.]
 [ 0.  0. -0. -1.]]


In [ ]:
print(cnot(0,1,2)@tensor([np.eye(2), z])@cnot(0,1,2))
print(tensor([z,z]))

[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


In [ ]:
print(cnot(0,1,2)@tensor([z, z])@cnot(0,1,2))
print(tensor([np.eye(2),z]))

[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0. -1.]]


In [ ]:
print(tensor([sigmax(), np.eye(2)])@tensor([np.eye(2),np.eye(2)])@tensor([sigmax(), np.eye(2)]))
print(tensor([np.eye(2),np.eye(2)]))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(tensor([sigmax(), np.eye(2)])@tensor([np.eye(2),np.eye(2)])@tensor([sigmax(), np.eye(2)]))
print(tensor([np.eye(2),np.eye(2)]))

In [9]:
print(sigmax()@z@sigmax())
print(-1 *z)


[[-1  0]
 [ 0  1]]
[[-1  0]
 [ 0  1]]


# Repetition Code Encoding



In [4]:
gates = [('CX', (0,1)),('CX', (0,2))]
stabs = ['IZI+', 'IIZ+']
print(gates)
evolve_stabilizers(stabs, gates)

[('CX', (0, 1)), ('CX', (0, 2))]


['ZZI+', 'ZIZ+']

# Random Coding Encoding

In [5]:
gates = randcircuit(3,5)
stabs = ['IZI+', 'IIZ+']
print(gates)
evolve_stabilizers(stabs, gates)

[('CX', (1, 2)), ('CX', (0, 1)), ('CX', (2, 0)), ('X', (1,)), ('X', (1,))]


['ZZZ+', 'ZZI+']

In [ ]:
gates = randcircuit(3,4)
print(gates)

Test XI, IX, XX, II

In [4]:
print(cnot(0,1,2)@tensor([np.eye(2),np.eye(2)])@cnot(0,1,2))
print(tensor([np.eye(2), np.eye(2)]))
#II

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
print(cnot(0,1,2)@tensor([sigmax(),np.eye(2)])@cnot(0,1,2))
print(tensor([sigmax(),sigmax()]))
#XI

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


In [10]:
print(cnot(0,1,2)@tensor([np.eye(2),sigmax()])@cnot(0,1,2))
print(tensor([np.eye(2),sigmax()]))
#IX

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [11]:
print(cnot(0,1,2)@tensor([sigmax(),sigmax()])@cnot(0,1,2))
print(tensor([sigmax(),np.eye(2)]))
#XX

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [13]:
print(sigmax()@sigmax()@sigmax())
print(sigmax())

[[0 1]
 [1 0]]
[[0 1]
 [1 0]]


In [16]:
gates = [('CX', (0,1)),('CX', (0,2))]
stabs = ['IZI+', 'IIZ+']
log = ['XII+', 'ZII+']
print(gates)
print(log)
evolve_stabilizers(stabs, gates, log)

[('CX', (0, 1)), ('CX', (0, 2))]
['XII+', 'ZII+']


(['ZZI+', 'ZIZ+'], ['XXX+', 'ZII+'])