In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np 
from stabilizer import *

In [ ]:
print(cnot(0,1, 3)@tensor([one, zero, zero]))
print(tensor([one,one,zero]))

In [7]:
s_zero = tensor([np.eye(2), z])
gate = cnot(0,1,2)
s_one = next(s_zero, gate)
print(s_one)
print(tensor([z,z]))

[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


Repetition Code:

In [8]:
A_zero = tensor([np.eye(2), z, np.eye(2)])
B_zero = tensor([np.eye(2), np.eye(2), z])
gate1 = cnot(0,1,3)
A_one = next(A_zero, gate1)
B_one = next(B_zero, gate1)

In [9]:
print(A_one)
print(tensor([z, z, np.eye(2)]))

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0.  0.  0.]
 [ 0.  0. -0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -0.  0.  0.]
 [ 0.  0.  0.  0. -0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [10]:
print(B_one)
print(tensor([np.eye(2), np.eye(2),z]))

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -1.  0. -0.  0. -0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0. -0.  0. -0.  0. -1.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0. -0.  0. -0.  0. -0.  0. -1.]]


In [11]:
gate2 = cnot(0,2,3)
A_two = next(A_one, gate2)
B_two = next(B_one, gate2)

In [12]:
print(A_two)
print(tensor([z,z, np.eye(2)]))

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0.  0.  0.]
 [ 0.  0. -0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -0.  0.  0.]
 [ 0.  0.  0.  0. -0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [13]:
print(B_two)



[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [ ]:
print(cnot(0,2, 3)@tensor([one, zero, one]))
print(tensor([one,zero,zero]))

In [ ]:
print(cnot(0,2, 3)@tensor([zero, zero, zero]))
print(tensor([zero,zero,zero]))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1. -0.]
 [ 0.  0. -0. -1.]]


[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


In [31]:
print(cnot(0,1,2)@tensor([z, z])@cnot(0,1,2))
print(tensor([np.eye(2),z]))

[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
[[ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0. -1.]]
